import React from "react";
import "../index.css"

export default function Abouts() {
  return (
    <section className="py-28 aboutSection ">
      <div className="container mx-auto text-center ">
        <h2 className="font-sans Montserrat  text-2xl font-bold text-amber-500	  mb-8">
          About Us
          
        </h2>
        <p className=" font-sans	 Montserrat text-2xl  text-gray-700   font-medium	 mx-auto">
          <span className="text-[#5DB85E] ">  </span>
            Environment and Engineering Research Center Pvt. Ltd is a consulting and research
institute registered in 6th May 2016 in the Office of Company Registrar at Tripureshwor,
Kathmandu. 
        </p>
        <br></br>
        <p className=" font-sans	 Montserrat text-base  text-gray-600   font-medium	 mx-auto p-6">
        The Environment and Engineering Research Center Pvt. Ltd has an interdisciplinary
team dedicated to understand the problems of development field relating to environment nexus and
their potential solutions. The organization is built on a foundation of scientific excellence,
interdisciplinary perspective and the momentum generated by dynamic researcher. in the field of
development including environmentalists, engineer, agriculture specialist, IT professional, and
other.
        </p>
        <p className=" font-sans	 Montserrat text-base  text-gray-600   font-medium	 mx-auto p-6">
        The organization aims to perform high quality scientific research and consulting in the
development field. Similarly, Environment and Engineering Research Center intend to conduct
short course, training, workshop and conference on environmental and engineering field. Similarly,
the organization aim to support and collaborate with scientists, researcher, policy maker and
decision maker in the field of environment and engineering.
        </p>

        <p className=" font-sans	 Montserrat text-base  text-gray-600   font-medium	 mx-auto">
          Join us on this journey towards sustainable development, where
          scientific rigor meets practical solutions. At EERC, we envision a
          future where environmental challenges are met with innovative
          engineering and collaborative efforts, paving the way for a harmonious
          and sustainable world.
        </p>
      </div>
    </section>
  );
}
